---

info:
  description: Training configuration repo

spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://jhagen1908:timmy@eureka-nonradiating-footnote.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  
