---
spring:  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  profiles: local
   
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/company
      username: user
      password: password
      driver-class-name: com.mysql.jdbc.Driver
      
  profiles: production
  
message: Purple squirrels are the greatest

