--- 
endpoints: 
  sensitive: false
message: "Nightshroud is the best class"
server: 
  port: 8100
spring: 
  jackson: 
    default-property-inclusion: NON_NULL
  jpa: 
    hibernate: 
      ddl-auto: update
    show-sql: true