---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: NON_NULL
 
 endpoints:
   sensitive: false
 
 server:
   port: 8100
  
 message: Nightshroud is the best class